### PR TITLE
fix: Disable Hardware Authenticator identities for unsupported Neighborhoods

### LINKED ISSUE #42: Hardware Authenticators not compatible with KvStore
One can create/import a hardware authenticator MANY identity when using a kvstore backend. The application should not display the option to the user as the kvstore backend does not currently support hardware authenticator.

### LINKED ISSUE #68: Disable `Hardware Authenticator` entry if neighborhood doesn't support it
See https://github.com/liftedinit/alberto/issues/135

@stanleyjones

### LINKED ISSUE #69: Unable to list Ledger info
One is stuck in an infinite loop when creating a new HSM account. The same is happening when importing said HSM account and displaying the Ledger info.

@stanleyjones

### PR DESCRIPTION
**Pull request by stanleyjones**
### Supported Neighborhood

Screenshot 2023-09-14 at 11 15 27 AM

### Unsupported Neighborhood

Screenshot 2023-09-14 at 11 15 37 AM

### Switching to an Unsupported Neighborhood

Screenshot 2023-09-14 at 11 22 21 AM

Closes #68 
Closes #42
Closes #69

### CODE REVIEW

File: src/api/neighborhoods/provider.tsx [hunk 1]
```diff
@@ -48,3 +48,21 @@ export function NeighborhoodProvider({ children }: { children: ReactNode }) {
     </NeighborhoodContext.Provider>
   );
 }
+
+export async function getServices(
```
Comment (stanleyjones) [inline src/api/neighborhoods/provider.tsx:52]: If we find a function like this useful in other places I could see it getting added to ManyJS.

File: src/features/accounts/components/accounts-menu/add-account-modal.tsx [hunk 2]
```diff
@@ -164,26 +181,31 @@ const createCards = [
...
-          <AddAccountCard
-            key={idx}
-            label={c.label}
-            title={c.title}
-            onClick={() => onAddMethodClick(c.onClickArg)}
-          />
-        );
-      })}
+      {createCards
+        .filter((c) => !c.requires || services.has(c.requires))
```
Comment (stanleyjones) [inline src/features/accounts/components/accounts-menu/add-account-modal.tsx:198]: Here's the visibility logic: Either don't have a requirement or have a satisfied requirement.

File: src/features/accounts/components/accounts-menu/add-account-modal.tsx [hunk 3]
```diff
@@ -203,25 +225,30 @@ const importCards = [
...
-          <AddAccountCard
-            key={idx}
-            label={c.label}
-            title={c.title}
-            onClick={() => onAddMethodClick(c.onClickArg)}
-          />
-        );
-      })}
+      {importCards
+        .filter((c) => !c.requires || services.has(c.requires))
```
Comment (stanleyjones) [inline src/features/accounts/components/accounts-menu/add-account-modal.tsx:241]: Same here.

**Comment by stanleyjones** [comment]
If this solution is acceptable I'll apply it to liftedinit/alberto#135 too.

**Comment by stanleyjones** [comment]
Investigating CI failure.

File: src/api/neighborhoods/provider.tsx (hunk 1 above)
Comment (jgryffindor) [reply src/api/neighborhoods/provider.tsx:52]: Yeah, this definitely looks useful in other contexts to discover what's available!

**Comment by jgryffindor** [comment]
I tested this on https://dev002_gwen.liftedinit.tech/ and functionally looks good!

**Review by fmorency — COMMENTED** [review]
I like it, thanks @stanleyjones 

@jgryffindor can we deploy this on QA? I want to test using an HSM.

**Review by fmorency — CHANGES_REQUESTED** [review]
I tested using a Yubikey on https://qa-gwen.liftedinit.tech/. 

The identity switch to `Anonymous` selecting an unsupported network doesn't work. Instead, it asks me to touch the key. The new network is selected, but the identity stays the same.

**Comment by jgryffindor** [comment]
When trying to import my existing ledger wallet I get an error "You're using a security key that's not registered..." and when creating a new account I get an error for Anonymous as well. 

image

**Comment by fmorency** [comment]
@jgryffindor the first error is expected. The other is not. Did you select the `QA Ledger` network when creating the new account?

**Comment by jgryffindor** [comment]
Woops, yah disregard the 2nd.

**Comment by stanleyjones** [comment]
@fmorency @jgryffindor How are you able to create an HSM identity on qa-gwen.liftedinit.tech? I receive the following error when I try:

```
Could not verify the signature: Unknown error: Anonymous requires no key id.,
Could not verify the signature: signature error., Unknown error: Origin not allowed.
```

Is this the error you're experiencing in liftedinit/gwen#69 ?

File: src/features/accounts/components/accounts-menu/accounts-menu.tsx [hunk 4]
```diff
@@ -66,7 +68,25 @@ export function AccountsMenu() {
...
   );
 
-  const [editAccount, setEditAccount] = React.useState<
+  const toast = useToast();
+  const { services } = useNeighborhoodContext();
+  useEffect(() => {
+    (async () => {
+      const isWebAuthnIdentity =
+        activeAccount?.identity instanceof WebAuthnIdentity;
+      if (isWebAuthnIdentity && !services.has("idstore")) {
```
Comment (stanleyjones) [inline src/features/accounts/components/accounts-menu/accounts-menu.tsx:77]: Getting the list of services is no longer asynchronous, which I suspect was causing a problem here.

File: src/features/accounts/components/accounts-menu/add-account-modal.tsx [hunk 5]
```diff
@@ -172,18 +173,21 @@ function CreateAccountOptions({
 }: {
   onAddMethodClick: (method: AddAccountMethodTypes) => void;
 }) {
+  const { services } = useNeighborhoodContext();
```
Comment (stanleyjones) [inline src/features/accounts/components/accounts-menu/add-account-modal.tsx:176]: Now that services is part of the context, I just pull it out at the component level instead of setting it in the container and passing it down through props.

**Review by stanleyjones — COMMENTED** [review]
Made some changes to the NeighborhoodContext to address the current problems.

1. NeighborhoodContext now provides both a query and a command network.
2. The set of services is updated when the neighborhood changes, not by the component.

**Comment by jgryffindor** [comment]
Test is deployed to QA @stanleyjones

**Comment by fmorency** [comment]
I tested the feature in QA and it doesn't appear to work. I imported an existing account from the QA Ledger. The account was imported but Gwen reverted back to Anonymous instantly. Selecting the HSM account from the account menu always reverts back to Anonymous, even if the network has HSM support.

**Comment by stanleyjones** [comment]
> Is there a reason why you diverged from how Alberto is doing this? We already had support for query/command/legacy `Network` in the `NetworkContext`. I think I prefer your version but still, we should reconcile things at some point.

Agreed that they need to be reconciled. My thought process was this:

- Hmm... Alberto has something different but I don't know what "legacy networks" are. Let's make sure they can be added in the future.
- Even though JavaScript will let you, I don't like the idea of an array where the first two elements are of the same type but optional and the third and fourth elements are arrays of two different types.
- I'll make it an object so everything has a clear name and people don't have to remember/guess which position is which thing. Then if we need to add legacy networks to Gwen, we won't have to change the order of everything.

Otherwise I think the context would be `[Network?, Network?, Network[], Set<string>]` which is a little cringe.

**Comment by fmorency** [comment]
> Hmm... Alberto has something different but I don't know what "legacy networks" are. Let's make sure they can be added in the future.

Yeah :(. This is a workaround for the chain breakage we had a while ago. Time was of the essence and I never revisited this (bad) design.

> I don't like the idea of an array where the first two elements are of the same type but optional and the third and fourth elements are arrays of two different types.

Yes, I agree.

> Otherwise I think the context would be `[Network?, Network?, Network[], Set<string>]` which is a little cringe.

Thanks for reworking that shady part of the code. I will port your design to Alberto and take this opportunity to rework the workaround mess.

**Comment by stanleyjones** [comment]
I believe I found the bug. Services were being correctly fetched but not set in the context object used by the account menu component. I still can't fully test this locally since I can't import an HSM for `localhost` but I've confirmed that the check for `idstore` passes when connected to a neighborhood with that module (i.e. the second half of this conditional, which previously was _always_ true `if (isWebAuthnIdentity && !services.has("idstore"))`).

**Comment by fmorency** [comment]
@jgryffindor can we deploy this on QA for testing please?

**Comment by jgryffindor** [comment]
QA Gwen is updated. Definitely looks better! When switching to a kvstore network with HSM selected I get alerted the network doesn't support it.  https://qa-gwen.liftedinit.tech

**Review by fmorency — APPROVED** [review]
The issue appears to be fixed, thanks.

nit: selecting `QA Ledger` and then selecting `Demo Compute` or `Demo KvStore` keeps the HSM identity. The other networks behave properly.

@stanleyjones I'll let you decide if you want to merge as-is or fix it in this PR. Anyhow, you can merge.

**Comment by stanleyjones** [comment]
It looks like it's getting a CORS error when trying to connect to those networks, so it keeps the list of available services from the previous network. I made it reset each time and handle the error.

**Comment by stanleyjones** [comment]
Waiting for CI and then I'll merge.
